// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'state/models/movement.model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(2, 7656930703731196),
      name: 'MovementModel',
      lastPropertyId: const IdUid(7, 8777093216612398992),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 731353403043962057),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 5552359023503114329),
            name: 'title',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 8666160016591586519),
            name: 'category',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 322784265091876348),
            name: 'price',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 8526203928865511708),
            name: 'image',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 256798981254180608),
            name: 'month',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(7, 8777093216612398992),
            name: 'type',
            type: 6,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Open an ObjectBox store with the model declared in this file.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// ObjectBox model definition, pass it to [Store] - Store(getObjectBoxModel())
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(2, 7656930703731196),
      lastIndexId: const IdUid(0, 0),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [378810589298808108],
      retiredIndexUids: const [],
      retiredPropertyUids: const [
        168271777215888504,
        7358120642630997158,
        9072664659983844564,
        1914719460084255166,
        575020497912633193,
        3520191793809871621,
        5527366738124074881
      ],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    MovementModel: EntityDefinition<MovementModel>(
        model: _entities[0],
        toOneRelations: (MovementModel object) => [],
        toManyRelations: (MovementModel object) => {},
        getId: (MovementModel object) => object.id,
        setId: (MovementModel object, int id) {
          object.id = id;
        },
        objectToFB: (MovementModel object, fb.Builder fbb) {
          final titleOffset = fbb.writeString(object.title);
          final categoryOffset = fbb.writeString(object.category);
          final imageOffset = fbb.writeString(object.image);
          fbb.startTable(8);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, titleOffset);
          fbb.addOffset(2, categoryOffset);
          fbb.addFloat64(3, object.price);
          fbb.addOffset(4, imageOffset);
          fbb.addInt64(5, object.month);
          fbb.addInt64(6, object.type);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = MovementModel(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, ''),
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 10, 0),
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, ''),
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 12, ''),
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0),
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0));

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [MovementModel] entity fields to define ObjectBox queries.
class MovementModel_ {
  /// see [MovementModel.id]
  static final id =
      QueryIntegerProperty<MovementModel>(_entities[0].properties[0]);

  /// see [MovementModel.title]
  static final title =
      QueryStringProperty<MovementModel>(_entities[0].properties[1]);

  /// see [MovementModel.category]
  static final category =
      QueryStringProperty<MovementModel>(_entities[0].properties[2]);

  /// see [MovementModel.price]
  static final price =
      QueryDoubleProperty<MovementModel>(_entities[0].properties[3]);

  /// see [MovementModel.image]
  static final image =
      QueryStringProperty<MovementModel>(_entities[0].properties[4]);

  /// see [MovementModel.month]
  static final month =
      QueryIntegerProperty<MovementModel>(_entities[0].properties[5]);

  /// see [MovementModel.type]
  static final type =
      QueryIntegerProperty<MovementModel>(_entities[0].properties[6]);
}
